export const ROLES = Object.freeze({
  CUSTOMER: "CUSTOMER",
  AGENT: "AGENT",
  UNDERWRITER: "UNDERWRITER",
  CLAIMS_ADJUSTER: "CLAIMS_ADJUSTER",
  CUSTOMER_SERVICE: "CUSTOMER_SERVICE",
  COMPLIANCE_OFFICER: "COMPLIANCE_OFFICER",
  ADMIN: "ADMIN"
});